---
title: "Import Data 2023-03-07"
author: "Andrii Hovorov"
date: today
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
    theme: cosmo
    code-fold: false
execute:
  warning: false
  message: false
---

## About

This is Qmd document for importing Noradrenaline project patch data

### Setup packages

```{r setup}
library(readABF)
library(tidyverse)
library(DT)
```

## Cell: 2023_03_07

First, let's just import one file

```{r import_file}
# import one example file
path_abf <- "../data/2023-03-07/2023_03_07_0001.abf"
example_file <- readABF(path_abf)

# make data tidy

head(as.data.frame(example_file, sweep = 1))

# define a function for sweeps extraction
extract_sweep <- function(sweep_n, abf) {
  abf %>%
    as.data.frame(sweep = sweep_n) %>% 
    mutate(sweep = sweep_n)
}

# test on example and extract sweep 1
head(extract_sweep(1, example_file))

# map to extract all sweeps from example file
sweeps_dfs <- map(1:length(example_file$data), ~ extract_sweep(sweep_n = .x, abf = example_file))

# bind rows to create a single dataframe
example_df <- bind_rows(sweeps_dfs)

# define a function to extract all sweeps from different files
abf_to_df <- function(abf) {
  map(1:length(abf$data), extract_sweep, abf = abf) %>%
    bind_rows()
}

# test on example file
head(abf_to_df(example_file))
```

## Now import all the data from the cell

```{r real_import}

# list the files from the target directory
files <- list.files(
  "../data/2023-03-07", 
  pattern = ".abf",  
  full.names = TRUE
  )

# read all files in the directory
abfs <- map(files, readABF)
# convert files into data frames
dfs <- map(abfs, abf_to_df)

# extract file subname to change naming of dataframes
files |> str_sub(-9, -5)

# name dataframes corresponding to their file
names(dfs) <- str_sub(files, -9, -5)

# make better column names (on example)
invisible(example_df |> rename(
  time_s = `Time [s]`,
  current_pA = any_of(c("Currnt0Pr [pA]", "Volt0Pr [pA]"))
))
datatable(head(example_df, n=15))

# make better column names on all dataframes
dfs <- map(
    dfs, 
    rename,  
    time_s = `Time [s]`,  
    current_pA = any_of(c("Currnt0Pr [pA]", "Volt0Pr [pA]"))
    )
# select only necessary columns (drop voltage)
dfs <- map(dfs, select, time_s, current_pA, sweep)

# merge all dataframes into single one 
# and introduce file name variable
all_sweeps <- bind_rows(dfs, .id = "file")

```

## Add parsed annotation from .txt file 

Here we add the variables for stimulation tyoe and condition (control, noradrenaline, washout)

```{r add_annotation}

all_sweeps <- all_sweeps %>%
    # only the files with AC or C stim, there is no recordings of 
    # A-stim in Noradrenaline so no need to import it
    filter (file %in% c("_0001", "_0002", "_0007", "_0011")) %>%
    mutate(
        # type of fibers stimulated in this file / sweep (C or both A and C)
        stim = case_when(
            file %in% c("_0001", "_0002") ~ if_else(sweep <= 10, "AC", "C"),
            file %in% c("_0007", "_0011") ~ if_else(sweep <= 7, "AC", "C")
        ),
        # condition of recording (control, noradrenaline, washout)
        cond = case_when(
            file %in% c("_0001", "_0002", "_0007") ~ "control",
            file %in% c("_0011") ~ "noradrenalin"
        )
    ) %>%
    mutate(
        stim = as.factor(stim),
        cond = as.factor(cond),
    )

```

```{r check_all_sweeps}
# checking the final dataframe
knitr::kable(head(all_sweeps, 10))
```

## Write data into file

```{r}

write_tsv(all_sweeps, file = "all_sweeps.tsv")

```


## Calculate passive parameters

```{r passive}

voltage_step_data <- all_sweeps |>
    filter(between(time_s, 0.12, 0.22))

baseline_tw <- c(0.14, 0.16)
peak_tw <- c(0.159, 0.165)
plateau_tw <- c(0.180, 0.198)

plot_voltage_step <- ggplot(voltage_step_data, 
       aes(x = time_s, 
           y = current_pA, 
           group = interaction(file, sweep),
           color = file)
       ) +
    geom_vline(xintercept = baseline_tw, color = "lightblue") +
    geom_vline(xintercept = peak_tw, color = "pink") +
    geom_vline(xintercept = plateau_tw, color = "green") +
    geom_line(alpha = 0.6)

ggplotly(plot_voltage_step)

voltage_step_data |> 
    group_by(file, sweep)  |>
    summarise(
        baseline = mean(current_pA[between(
            time_s, 
            baseline_tw[1], 
            baseline_tw[2])]),
        peak = mean(current_pA[between(
            time_s, 
            peak_tw[1], 
            peak_tw[2])]) - baseline,
        plateau_pA = mean(current_pA[between(
            time_s, 
            plateau_tw[1], 
            plateau_tw[2])]),
        Rs_MOhm = -10000/peak,
        Rtotal_MOhm = -10000/ plateau_pA,
        Rmemb_MOhm = Rtotal_MOhm - Rs_MOhm
    )

```


## Session info

```{r session_info}
sessionInfo()
```

