---
title: "Import_2025_05_02"
author: "Ivan Blashchak"
date: today
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
    theme: cosmo
    code-fold: true
    
execute:
  warning: false
  message: false
---

## About

This is .Qmd document for importing patch clamp data for cell 2025_05_02


```{r setup}

# install.packages("readABF")
library(readABF)
library(tidyverse)
library(DT)

```

## Cell: 2025_05_02

First lets just import one file

```{r import_file}

#import one example file
example_file <- readABF("../data/2025_05_02/2025_05_02_0005.abf")

# make data tidy
# as.data.frame(example_file, sweep = 1)

extract_sweep <- function(sweep_n, abf){
    abf |>
        as.data.frame(sweep = sweep_n) |>
        mutate(sweep = sweep_n)
}

# extract_sweep(sweep_n = 1, abf = example_file)

sweep_dfs <- map(1:length(example_file$data), extract_sweep, abf = example_file)

example_df <- bind_rows(sweep_dfs)

abf_to_df <- function(abf){
    map(1:length(abf$data), extract_sweep, abf = abf) |>
        bind_rows()
}

example_df <- abf_to_df(example_file)

datatable(head(example_df, 10000))

knitr::kable(head(example_df))
```

## Now import all data for the cell

``` {r real_import}

files <- list.files(
    "../data/2025_05_02/", 
    pattern = ".abf", 
    full.names = TRUE
    )

abfs <- map(files, readABF)

dfs <- map(abfs, abf_to_df)

files |> str_sub(-9,-5)

names(dfs) <- str_sub(files, -9,-5)

# example_df |> rename(
#     time_s = `Time [s]`,
#     current_pA = any_of(c("Currnt0Pr [pA]", "Volt0Pr [pA]"))
# )

dfs <- map(
    dfs, 
    rename, time_s = `Time [s]`, 
    current_pA = any_of(c("Currnt0Pr [pA]", "Volt0Pr [pA]"))
    )

dfs <- map(dfs, select, time_s, current_pA, sweep)

all_sweeps <- bind_rows(dfs, .id = "file")

datatable(head(all_sweeps, 10000))

```

## Annotate

Here we add the variables for stimulation type and 
condition (control, noradrenaline, washout)

```{r annotate}


all_sweeps <- all_sweeps %>%
    # for "_0006" only recordings before NA addition were included
    filter ( ! (file == "_0006" & sweep > 10)) %>%
    mutate(
        # type of fibers stimulated in this file / sweep (A, C or both)
        # in this cell only AC simulations were performed
        stim = case_when(
            file == "_0005" ~ if_else(sweep <= 17, "AC", "C"),
            file == "_0006" ~ "C",
            file == "_0007" ~ if_else(sweep <= 18, "AC", "C"),
            file == "_0008" ~ "AC"
        ),
        # condition of recording (control, noradrenaline, washout)
        cond = case_when(
            file %in% c("_0005", "_0006") ~ "control",
            file == "_0007" ~ "noradrenalin",
            file == "_0008" ~ "washout"
        )
    ) %>%
    mutate(
        stim = as.factor(stim),
        cond = as.factor(cond),
    )


datatable(head(all_sweeps, 10000))


```


```{r saving data}

write_tsv(all_sweeps, file = "../all_sweeps.tsv")


# saving only part of the data for shiny app to make it faster
write_tsv(all_sweeps |> filter(between(time_s, 0.1, 0.7)), 
file = "../all_sweeps_part.tsv")

```


## Calculate passive parameters

```{r passive}

# voltage_step data
voltage_step_data <- all_sweeps |>
    filter(between(time_s, 0.12, 0.22))

baseline_tw <- c(0.14, 0.16)
peak_tw <- c(0.159, 0.165)
plateau_tw <- c(0.180, 0.198)

plot_voltage_step <- ggplot(voltage_step_data, 
       aes(x = time_s, y = current_pA, group = interaction(file,sweep), color = file)
       )+
    geom_line(alpha = 0.6) +
    geom_vline(xintercept = baseline_tw, color = "lightblue") +
    geom_vline(xintercept = peak_tw, color = "pink") +
    geom_vline(xintercept = plateau_tw, color = "lightgreen")

ggplotly(plot_voltage_step)

voltage_step_data |>
    group_by(file,sweep) |>
    summarise(
        baseline_pA = mean(
            current_pA[between(time_s, baseline_tw[1], baseline_tw[2])]
            ),
        peak_pA = min(
            current_pA[between(time_s, peak_tw[1], peak_tw[2])]
            ) - baseline_pA,
        plateau_pA = mean(
            current_pA[between(time_s, plateau_tw[1], plateau_tw[2])]
            ) - baseline_pA,
        Rs_MOhm = -10000 / peak_pA,
        Rtotal_MOhm = -10000 / plateau_pA,
        Rmemb_MOhm = Rtotal_MOhm - Rs_MOhm
        )



datatable()


```


## Session info

```{r info}

sessionInfo()

```








